services:
    php:
        build:
            context: .
            target: php
            dockerfile: docker/Dockerfile
            args:
                uid: ${WWWUSER}
        environment:
            - PHP_USER=#${WWWUSER}
            - PHP_GROUP=#${WWWUSER}
        volumes:
            - ./:/var/www/html:rw
        networks:
            - internal
        restart: unless-stopped

    nginx:
        image: nginx:alpine
        ports:
            - ${APP_PORT}:80
            - 5173:5173
        volumes:
            - ./:/var/www/html:ro
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - internal
        depends_on:
            - php
        restart: unless-stopped

networks:
    internal:
        name: laravel-net
        driver: bridge
